# Builds and Pushes a Docker Image to DockerHub. It will get stored in the DockerRepo SmartCity.
# It uses a Ubuntu 20.04 OS
# It uses Docker official login action
# Uses Docker Build and Push Action to build and push the Image to DockerHub.
name: Full CI and CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      NEXT_PUBLIC_E2E_TEST: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Reset
        run: npx prisma migrate reset -f
      - name: Cypress run with env
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000
  notify:
    needs: cypress-run
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: merlinchiodo/smartcity:AmtfuerIntegration,merlinchiodo/smartcity:AmtfuerIntegration_1.0.0-${{ github.sha }}
